### ISSUE TITLE
Move to BareOS

### ISSUE THREAD

**Issue by rockyluke** [moul/scaleway-bareos#1]
You life will be better after that !

**Comment by moul** [comment]
Hey !

Is BareOS server compatible with bacula client ?

```
    ╚⊙ ⊙╝
  ╚═(███)═╝
 ╚═(███)═╝
╚═(███)═╝
 ╚═(███)═╝
  ╚═(███)═╝
   ╚═(███)═╝
    ╚═(███)═╝
    ╚═(███)═╝
```

**Comment by rockyluke** [comment]
Yes ! Actually we've started migration, only server's daemon, still bacula-fd client. work perfectly.

**Comment by moul** [comment]
ok, let's go for it, thanks !
